mercury-hpc/mercury

src/mercury.c, src/mercury.h, src/mercury_core.c, src/mercury_core.h
Convenience function for getting a bulk class from a mercury class. Especially useful when using an implicit bulk class (e.g. passing HG_BULK_NULL to HG_Init).
=> add hg to hg-bulk getters

src/util/mercury_request.h
Based on our conversation in the mailing list, hg_request functions shouldn't be used when called within an RPC handler.
=> put request library limitations up front

Examples/src/example_rpc_client.c, Examples/src/example_rpc_engine.c, Examples/src/example_rpc_engine.h
- The example program uses a dedicated thread to call HG_Progress,
which means that there will be contention if one of the other threads
calls NA_Addr_lookup_wait() (which internally will attempt to drive NA
progress on its own)
- Use asynchronous NA_Addr_lookup() instead
=> avoid calling lookup_wait in threaded example

src/mercury.c, src/mercury_core.c, src/mercury_core.h, src/mercury_proc.c, src/mercury_proc.h, src/mercury_proc_header.c, src/mercury_proc_header.h, src/na/na_bmi.c, src/na/na_cci.c, src/na/na_mpi.c
This makes Mercury use short sends for both requests and responses.  Rather than sending the full buffer that was pre-allocated to the maximum unexpected size reported by the NA transport, it only sends the portion of it that holds the encoded request or response struct and HG header.
For my example program with CCI/TCP on a loopback interface, this reduces the request/response sizes in bytes from 8988/8988 to 104/28.  I think this change will probably reduce RPC latency for all transports.
Fixes #68
=> use short sends for req/response

src/mercury_types.h, src/util/mercury_request.c, src/util/mercury_request.h
Simple function that should account for 90% of hg_request use cases (HG_Forward + hg_request_wait).
Also, noticed a doc error about returning -HG_XXX_ERROR, which doesn't seem to be done, and added an HG_OTHER_ERROR error type for errors outside the purview of mercury (such as mercury_util).
=> add hg_request_forward_cb convenience function

src/mercury.c, src/mercury.h, src/mercury_core.c, src/mercury_core.h, src/mercury_proc.h
See #142 for discussion. This initial implementation doesn't account for alignment/etc., unclear whether it's necessary.
=> [WIP] size getters for eager mode RPC arg xfers

src/util/mercury_atomic_queue.h
Check if its x86 before using cpu_spinwait, if not use
empty function now on other architectures.
=> Checking for x86 before using cpu_spinwait

Testing/na/na_test.c, src/na/na_ofi.c
Fixes #236 .
Does not resolve any other correctness issues, just gives us a cleaner starting point.
=> unify verbs and verbs;ofi_rxm path in na_ofi

src/na/na_ofi.c
Enables FI_THREAD_SAFE for verbs;ofi_rxm and removes extra mutex locks.
Per earlier email discussion with @liuxuezhao .
=> remove mutex around verbs provider path

src/na/na_ofi.c
FI_DIRECTED_RECV is supported when using the verbs;ofi_rxm provider stack.  Re-enable it to be consistent with other providers in na_ofi.c and gain an extra layer of safety on message matching.
Closes #244
=> re-enable FI_DIRECTED_RECV for ofi verbs provider

Testing/mercury_rpc_cb.c, Testing/mercury_rpc_cb.h, Testing/mercury_test.c, Testing/na/na_test.c, Testing/test_bulk.c, Testing/test_bulk.h, Testing/test_server.c, src/mercury_bulk.c, src/mercury_bulk.h, src/mercury_core.c, src/mercury_core.h, src/mercury_proc_bulk.h, src/na/na.c, src/na/na.h, src/na/na_bmi.c, src/na/na_cci.c, src/na/na_mpi.c, src/na/na_ofi.c, src/na/na_private.h, src/na/na_sm.c
HG Bulk: 
- add HG_Bulk_bind(), HG_Bulk_get_addr(), HG_Bulk_get_context_id()
- also add HG_Bulk_bind_transfer() for convenience
HG Bulk proc:
- enable caching of serialized bulk handles / cleanup
HG Core:
- add HG_Core_addr_create() and HG_Core_addr_set_na()
NA: 
- add NA_Addr_serialize()/NA_Addr_deserialize()/get_serialize_size() and corresponding plugin callbacks
NA OFI:
- Add na_ofi_addr_serialize() plugin callback implementation
- Rework address handling to only use native addressing format
- Fix passing of init node and domain info in na_ofi_initialize()
- Fix socket provider to bind to specific host/port (fix #207)
- Update gni provider to use FI_SOURCE | FI_SOURCE_ERR caps
- Rework and clean up na_ofi_progress()
- Allocate src_err_addr for fi_cq_readerr()
- Clean up NA OFI op ID …
=> Bulk: bind HG addr to bulk handle and NA OFI addressing fixes

src/na/na_bmi.c
- BMI send is asynchronous; stack variable could go out of scope by
transmission time.  Re-use flag already present in na_bmi_op_id that's
normally only used by initiator of put operation.
=> bmi_na: bug fix to put ctrl msg

src/mercury.c
- Don't skip too many header encoding steps if input struct and/or encoder is null.
- This fix ensures that Mercury includes the HG_Class_set_input_offset() area when transmitting RPCs with no input arguments.
=> fix bug in header encoding for null input

src/mercury.c, src/mercury.h
This is helpful for use cases where the caller doesn't need to know the buffer size and just wants to access the smaller region that they have reserved with HG_Class_set_input_offset().  
This patch does not change the semantics of the call for existing users.  It just allows new users to pass NULL for the last argument rather than declaring a dummy variable to hold the unwanted result.
=> allow NULL size argument to HG_Get_input_buf()

src/na/na_ofi.c
na_ofi_addr_lookup() always sets refcount of na_ofi_op_id to 1,
this is incorrect if this ID is passed in by caller.
This patch removes the assignment because na_ofi_op_create() has
already set it to 1 for the case of creation.
Signed-off-by: Liang Zhen <liang.zhen@intel.com>
=> refcount of na_ofi_op_id is overwritten

Testing/test_rpc.c, src/mercury.c, src/mercury.h, src/mercury_core.c, src/mercury_core.h, src/na/na.c, src/na/na.h, src/na/na_bmi.c, src/na/na_cci.c, src/na/na_mpi.c, src/na/na_ofi.c, src/na/na_sm.c
Prevent some extra allocations
Allow for unexpected and deserialized addresses to be converted to strings
=> NA OFI: refactor internal handling of addresses

Testing/na/na_test.c, Testing/na/na_test.h, Testing/na/na_test_getopt.c, src/na/na_ofi.c
Users can now pass: ofi+protocol://domain/iface:port
(e.g., ofi+verbs://mlx5_0/ib0:12345)
Are also valid:
- ofi+protocol://domain/hostname:port
- ofi+protocol://domain
- ofi+protocol://iface
- ofi+protocol://hostname
- ofi+protocol://domain/iface
- ofi+protocol://domain/hostname
- ofi+protocol://iface:port
- ofi+protocol://hostname:port
Update NA tests to use domain name
=> NA OFI: allow for passing explicit domain name (fixes #297)

src/mercury_core_types.h
May be used by RPC callback to return error codes back to client
=> HG: add HG_OTHER_ERROR return code back

Testing/na/CMakeLists.txt, Testing/na/test_lat_client.c, Testing/util/test_poll.c, src/mercury_core.c, src/na/na_sm.c, src/util/mercury_poll.c, src/util/mercury_poll.h
This simplifies the current polling mechanism by no longer using callbacks for hg_poll_add() routines and unifies previous hg_core_progress_na() and hg_core_progress_poll() routines. It also prevents extra stack allocations by preallocating event arrays.
=> Rework of HG polling mechanism

src/mercury_bulk.c
When the bulk transfer failed, should increase op_completed_count
and complete the bulk when needed, or the bulk possibly cannot complete
forever.
Signed-off-by: Xuezhao Liu <xuezhao.liu@intel.com>
=> bulk: fix an bug in hg_bulk_transfer_cb

src/na/na_sm.c
This slightly alters the logic in na_sm_progress() so that it calls epoll_wait() (by way of hg_poll_wait()) even when the timeout is zero as long as a poll_set is present.
The reason is for performance; if the poll_wait() is not called, then na_sm must call both recvmsg() and read() in case unexpected messages are present.  The former in particular is more expensive than epoll_wait() with a zero timeout.
Output below shows the average response time difference (dropped from 3.3 usec to 2.6 usec) for a Mochi sdskv benchmark with a single process.  This example is not actually doing any na communication at all (all operations are "self" RPCs), but there is a performance difference anyway because mercury must check the active na+sm transport on every iteration.
```
test case: …
```
=> use epoll_wait() in na_sm even with timeout 0

src/util/mercury_time.h
in milliseconds.  The UCX plugin will use this.
=> Add hg_time_from_ms() for making an hg_time_t from an integer duration

src/util/mercury_thread_condition.c, src/util/mercury_thread_condition.h
CLOCK_MONOTONIC_COARSE cannot be passed to pthread_condattr_setclock or it causes pthread_cond_timedwait() to return early. This was causing HG_Trigger() to excessively spin when a timeout was passed.
=> HG util: fix timeout passed to pthread_cond_timedwait()

src/mercury_core.c, src/util/mercury_poll.c
Returning an error when adding a file descriptor lower than STDERR_FILENO
was causing errors when users were closing those std file descriptors
=> HG util: remove check for STDERR_FILENO (fix #428)

src/na/na_ofi.c
When not yielding, a thread dedicated to progress would busy spin and not allow for other threads to be scheduled.
=> NA OFI: yield to other threads when using PSM2

src/util/mercury_request.c, src/util/mercury_time.h
The previous countdown to timeout was hard to follow, and I wasn't sure about using a double to keep the time remaining.
This change compares the current time with an hg_time_t deadline to see if it's
time to exit. Should still run through the loop at least once if the timeout is 0 milliseconds.
I added a new utility function, hg_time_to_ms(), for converting an hg_time_t directly
to integer milliseconds.
=> hg_request_wait(): simplify timeout logic & arithmetic

src/util/CMakeLists.txt, src/util/mercury_log.c, src/util/mercury_util_config.h.in
Add CMake check for __attribute__((constructor(priority)))
=> HG util: fix log initialization with constructor priority (fix #454)

src/na/na_ip.c, src/na/na_ip.h, src/na/na_ofi.c, src/na/na_ucx.c
… for tcp provider
Clean up ip and domain checking
NA IP: refactor na_ip_check_interface() to only use getaddrinfo() and getifaddrs()
Add family argument to force detection of IPv4/IPv6 addresses
=> NA OFI: use NA IP check module and add missing NA_OFI_VERIFY_PROV_DOM

src/na/CMakeLists.txt, src/na/na_config.h.in, src/na/na_ofi.c
Clean up provider table and add EP proto
Add support for FI_MR_ENDPOINT mr mode
Co-authored-by: Alexander A Oganezov <alexander.a.oganezov@intel.com>
=> NA OFI: add support for HPE CXI provider

src/mercury_core.c, src/mercury_core_types.h
Modify behavior of stats field to turn on diagnostics
=> HG Core: keep 'stats' fields removed in previous commit

Testing/mercury_test.c, src/na/na_ofi.c
HG Test: check that length returned can be used in second call
=> NA OFI: fix regression introduced in na_ofi_addr_to_string()

src/na/na_ip.c, src/na/na_loc.c, src/na/na_loc.h, src/na/na_ofi.c
(fix #554)
Separate fabric from domain and keep single domain per NA class
Refactor handling of scalable vs standard endpoints
Improve debug info to print verbose FI info of selected provider
=> NA OFI: rework handling of fi_info to open fabric/domain/endpoint

Testing/na/na_test.c, Testing/na/na_test.h, Testing/na/na_test_getopt.c, Testing/na/na_test_perf.c, Testing/na/na_test_perf.h, Testing/na/test_bw_get.c, Testing/na/test_bw_put.c, Testing/na/test_lat.c, Testing/na/test_perf_server.c
Add -M option to print output in OSU-style Million Bytes/s
Allocate page-size aligned RMA buffers
Clean up and simplify perf tests
=> NA Test: add -w option to control RMA buffer count (default is 64)

src/na/na_ofi.c
This prevents from having providers return invalid keys when MR cache is also used
=> NA OFI: when using FI_MR_ENDPOINT retrieve key after fi_mr_enable() call

Testing/CMakeLists.txt, src/na/na_ofi.c
This prevents a performance regression when multiple classes are being used
FI_THREAD_DOMAIN is therefore disabled for these providers
=> NA OFI: force sockets and tcp providers to use shared domains

src/mercury_core.c
Increment the counter before sending in case hg_core_handle is released soon by another thread as a consequence of the forward.
=> HG: fix race condition in hg_core_forward with debug enabled

src/na/na_ofi.c
Instead of using the strtok_r saveptr argument which is suppose to be opaque, use strstr to find the location of :. This makes the code slightly simpler and removes some warning brought up by some static code analysis tools.
=> NA OFI: Use strstr instead of strtok_r to parse URI

src/mercury_core.c
The previous code performs the following operation even if hg_init_info is NULL: &hg_init_info->na_init_info.
This works correctly as na_init_info is the first field of struct hg_init_info.
This change explicitly tests for NULL pointer. Thus, making the code more explicit and simpler to understand (not relying on the order of the fields in the struct). It also avoids the issue being flagged by some code analysis tools.
=> HG: Avoid getting pointer of field if struct pointer is NULL

Testing/perf/hg/hg_bw_read.c, Testing/perf/hg/hg_bw_write.c, Testing/perf/hg/mercury_perf.c, Testing/perf/hg/mercury_perf.h, Testing/perf/na/na_perf.c, Testing/unit/util/CMakeLists.txt, Testing/unit/util/test_mem.c, src/mercury_core.c, src/na/na_ofi.c, src/na/na_types.h, src/util/mercury_mem.c, src/util/mercury_mem.h
HG util: add support for hugepage allocations
Testing: add mem util test
HG Core: bump pre-allocated requests to 512 to make use of 2M hugepages
NA perf: update perf test to use hugepages
NA: fix some multi-recv constants
=> NA OFI: allocate multi-recv buffers using hugepages when available

src/util/mercury_atomic_queue.h
This is used by some projects like sse2neon and rust (https://github.com/rust-lang/rust/commit/c064b6560b7ce0adeb9bbf5d7dcf12b1acb0c807).
=> Use isb for cpu_spinwait on aarch64

src/na/na_ucx.c
This allows for reusing existing listener addr after a listener exits abnormally
=> NA UCX: set CM_REUSEADDR by default

src/util/mercury_atomic.h, src/util/mercury_mem.c
Multiple threads access the page_size variable without synchronization. Fix the issue by using atomics.
Also remove the usage of ATOMIC_VAR_INIT on recent compilers as it is now deprecated and unnecessary.
=> HG util: Fix race condition in hg_mem_get_[huge]page_size

Testing/common/mercury_test_config.h.in, Testing/unit/hg/mercury_unit.c, Testing/unit/hg/mercury_unit.h, Testing/unit/hg/test_rpc.c, src/mercury_config.h.in, src/mercury_core.c, src/mercury_private.h, src/na/na_ofi.c
Once NA_OFI_OP_RETRY_TIMEOUT milliseconds elapse, retry is stopped and operation is aborted (default is 120000ms)
When NA_OFI_OP_RETRY_PERIOD is set, operations are retried only every NA_OFI_OP_RETRY_PERIOD milliseconds (default is 0).
=> NA OFI: add NA_OFI_OP_RETRY_TIMEOUT and NA_OFI_OP_RETRY_PERIOD

src/mercury.c, src/mercury.h, src/mercury_core_types.h
Add release_input_early init info flag to release input buffers early
=> HG: disable early release of input buffers by default w/ multi_recv

src/na/na_sm.c, src/util/mercury_atomic.h, src/util/mercury_mem.c
ATOMIC_VAR_INIT has a trivial definition
`#define ATOMIC_VAR_INIT(value) (value)`,
is deprecated in C17/C++20, and will be removed in newer standards in newer GCC/Clang (e.g. https://reviews.llvm.org/D144196). Just remove the HG_ATOMIC_VAR_INIT wrapper.
=> Remove HG_ATOMIC_VAR_INIT

CMakeLists.txt
Newer versions of CMake ignore the property but older versions do not.
=> CMake: ensure VERSION/SOVERSION is not set on MODULE libraries

src/na/na_sm.c, src/util/mercury_atomic.h, src/util/mercury_mem.c
Revert commit 508bc98f111778f1fe64af336f16ba73df89f4fa for now as this would potentially cause initialization issues with WIN32/MacOS builds. Will re-apply once atomic support has been updated for those platforms.
=> HG util: Revert "Remove HG_ATOMIC_VAR_INIT"

Examples/CMakeLists.txt, Examples/src/example_rpc.c, Examples/src/example_rpc.h, Examples/src/example_rpc_client.c, Examples/src/example_rpc_engine.h, Examples/src/example_snappy.c, Examples/src/example_snappy.h, Examples/src/example_snappy_client.c, Testing/common/mercury_test.c, Testing/common/na_test.c, Testing/script/gh_install_deps.sh, Testing/script/gh_script.cmake, src/mercury.c, src/mercury.h, src/mercury_core.c, src/mercury_core.h, src/mercury_core_types.h, src/mercury_private.h, src/na/na.c, src/na/na.h, src/na/na_types.h
Add HG_Init_opt2() / NA_Initialize_opt2() routines and version info struct.
=> HG: prevent ABI breakage from updated info struct

CMakeLists.txt, src/mercury.h, src/mercury_core.c, src/mercury_core.h, src/na/na.c, src/na/na.h, src/na/na_bmi.c, src/na/na_cci.c, src/na/na_mpi.c, src/na/na_ofi.c, src/na/na_plugin.h, src/na/na_psm.c, src/na/na_sm.c, src/na/na_types.h, src/na/na_ucx.c, util/CMakeLists.txt, util/info.c
This gives the ability to query protocol info from plugins
Refactor check protocol code for static/dynamic plugins
NA OFI/UCX/SM: add support for get_protocol_info
Add na_protocol_info struct to na_types
NA OFI: ensure extra caps passed are honored by provider
---
`NA_Get_protocol_info("ofi+tcp", &info)` will give for example `"ofi, tcp, lo" "ofi, tcp, eth0"` with the list of domains or doing
`NA_Get_protocol_info("tcp", &info)` will give `"ofi, tcp, lo" "ofi, tcp, eth0" "ucx, tcp, lo" "ucx, tcp, eth0"`
or passing `NULL` in `info_string`
`NA_Get_protocol_info(NULL, &info)` will give a list of all supported protocols and domains/devices
=> NA: add NA_Get_protocol_info() / NA_Free_protocol_info() (#544)

Testing/common/na_test.c
Fix missing return check of na_test_mpi_init()
=> NA Test: do not use MPI_Init_thread() if not needed

Testing/perf/na/na_perf_server.c, src/na/na_sm.c, src/na/na_ucx.c
NA UCX: emit warning on connection error handler
NA SM: add perf warning message for unexpected messages without recv posted
NA perf: fix NA latency test to ensure recvs are always pre-posted
=> NA UCX: fix handling of unexpected messages without pre-posted recv

CMakeLists.txt
This fixes an issue seen on macOS where libraries would not be found using @rpath.
=> CMake: pass INSTALL_NAME_DIR through target properties

Testing/script/gh_install_deps.sh, src/mercury_core.c
Address an issue where HG_Context_unpost() would unnecessarily wait
=> HG Core: separate internal list from user created list of handles

Testing/common/CMakeLists.txt, Testing/common/mercury_test.c, Testing/common/na_test.c, Testing/common/na_test.h, Testing/common/na_test_mpi.c, Testing/common/na_test_mpi.h, Testing/perf/hg/hg_bw_read.c, Testing/perf/hg/hg_bw_write.c, Testing/perf/hg/hg_perf_server.c, Testing/perf/hg/hg_rate.c, Testing/perf/hg/mercury_perf.c, Testing/perf/na/na_perf.c, Testing/script/gh_script.cmake, Testing/unit/hg/mercury_unit.c
MPI can now be autodetected and dynamically loaded, even if MERCURY_TESTING_ENABLE_PARALLEL was turned off. If MERCURY_TESTING_ENABLE_PARALLEL is turned on, tests remain linked against MPI as they used to be.
Add client and server comm size information.
=> HG perf: autodetect MPI implementation

Testing/common/CMake/FindCXI.cmake, Testing/common/CMakeLists.txt, Testing/common/mercury_test_config.h.in, Testing/common/na_test.c, Testing/common/na_test.h, src/na/na_ofi.c
Requires libfabric >= 1.20
Add support for FI_AV_USER_ID
Add support for new CXI address format
Clean up handling of FI_SOURCE_ERR
Separate opening of AV and auth key insertion
Parse auth key range when listening (w/ FI_AV_AUTH_KEY)
Encode/decode auth key when serializing addrs
=> NA OFI: add support for FI_AV_AUTH_KEY

src/mercury_core.c, src/mercury_core_types.h, src/mercury_private.h, src/na/na.c, src/na/na.h, src/na/na_types.h
Fix HG NA init info to v4.0 for now and duplicate tclass info
=> HG/NA: fix init info changes made to prevent ABI breakage

src/mercury.c, src/mercury_proc.h
hg_proc_get_handle() can be used to retrieve handle from proc
=> HG: associate handle to HG proc

src/mercury_core.c, src/mercury_core_types.h, src/mercury_private.h
Use these two new parameters to fallback to memcpy to prevent starvation of multi-recv buffers and potential deadlock situations.
=> HG Core: add copy_on_multi_recv and multi_recv_copy_threshold

src/mercury_core.h, src/mercury_proc.h
HG proc: fix handle field added that would have broken ABI
=> HG proc/core: fix couple of type changes that could have broken ABI

Testing/unit/hg/mercury_rpc_cb.c, Testing/unit/hg/mercury_unit.h, Testing/unit/hg/test_rpc.c, src/mercury.c, src/mercury.h, src/mercury_core.c, src/mercury_core.h, src/na/na_bmi.c, src/na/na_mpi.c
Add the ability to query input / output payload sizes
Update tests to use new routines
=> HG: add HG_Get_input/output_payload_size() (fix #751)

Testing/perf/hg/hg_bw_read.c, Testing/perf/hg/hg_bw_write.c, Testing/perf/hg/mercury_perf.c, Testing/perf/hg/mercury_perf.h, src/na/na_ofi.c
Also disable PROV_KEY_CACHE
Add NA_OFI_SKIP_DOMAIN_OPS env variable to skip domain ops
=> NA OFI: fix cxi domain ops settings

Documentation/CHANGES.md, src/mercury.c, src/mercury_core_types.h, src/na/na.c
Check errnum value in string conversion
=> HG: fix RETURN_VALUES macro to only take single argument (fix #766)

src/mercury_bulk.c
=> HG bulk: fix possible erroneous refcount when bulk create/transfer fails

Testing/unit/hg/mercury_rpc_cb.c, Testing/unit/hg/test_rpc.c, src/mercury.c, src/mercury_proc.h
Mercury configured with -DMERCURY_USE_XDR=ON fails to pass the unit tests. The main issue is that mercury was not properly accounting for the data padding that xdr uses.
When encoding, xdr pads all data added to its buffer to the next multiple of BYTES_PER_XDR_UNIT (4 bytes, see /usr/include/rpc/xdr.h) and provides a macro RNDUP(s) to round "s" up to the next multiple of BYTES_PER_XDR_UNIT.
The native mercury code (when not using xdr) does not pad data.  When mercury is compiled to use xdr it does not account for the padding xdr uses and gets out of sync with xdr.  Given an hg_proc_t "p" we need to make sure that hg_proc_get_size_used(p) is always equal to xdr_getpos(hg_proc_get_xdr_ptr(p)) after encoding a chunk.
To fix this we:
- modify the xdr version of HG_PROC_TYPE() in …
=> update -DMERCURY_USE_XDR=ON code to pass unit tests

src/mercury_proc.c, src/mercury_proc_bulk.c
hg_proc_hg_bulk_t() uses hg_proc_save_ptr() to allocate buffer space for encoding/decoding bulk handles, but it does not check the return value of hg_proc_save_ptr(). hg_proc_save_ptr() returns NULL on memory allocation failure. update hg_proc_hg_bulk_t() to check the return value of hg_proc_save_ptr() to see if it is NULL.
Update hg_proc_save_ptr():
When hg_proc_save_ptr() is compiled with !HG_HAS_XDR we should check the return value of hg_proc_set_size() for resize errors and fail if hg_proc_set_size() fails.
When hg_proc_save_ptr() is compiled with HG_HAS_XDR, we should follow the XDR BYTES_PER_XDR_UNIT rounding rules just in case the size is not a multiple of BYTES_PER_XDR_UNIT. If we run out of preallocated space we should fail (since XDR does not grow buffers).  Simplify code to use …
=> fix hg_proc_save_ptr() error handling and allocation (when using XDR)

Testing/unit/hg/test_bulk.c, Testing/unit/hg/test_rpc.c, src/mercury.c, src/mercury_proc.c, src/mercury_proc.h
Modify mercury proc code to use the same buffer management strategy for overflow in the HG_HAS_XDR case that we use in the non-xdr case.  To do this, we modify hg_proc_set_size() to sync the two fields in the XDR structure used by xdrmem with the hg_proc when the extra_buf info is updated.
Update xdr to use the normal version of HG_PROC_CHECK_SIZE() that calls hg_proc_set_size() if needed.
Update hg_proc_save_ptr() to call hg_proc_set_size() in the HG_HAS_XDR case when there is an overflow.
Enable overflow testing in Testing/unit/hg for HG_HAS_XDR (expected size calculations in the xdr case still must account for the xdr size rounding rules).
Additional cleanups:
- move XDR from hg_proc_buf struct to hg_proc struct (only one XDR is needed, the second one was never used).
- hg_proc_reset() …
=> HG proc: enable proc overflow for the HG_HAS_XDR case

CMakeLists.txt, src/mercury_config.h.in, src/mercury_core.c
In some cases, it may be useful to enable the counters without
enabling the full debugging configuration.
Signed-off-by: Michael MacDonald <mjmac@google.com>
=> enable diagnostic counters without debug

Testing/perf/hg/hg_perf_server.c, Testing/perf/hg/mercury_perf.c, Testing/perf/hg/mercury_perf.h, Testing/perf/na/na_perf.c, Testing/perf/na/na_perf.h, Testing/perf/na/na_perf_server.c
Reduce overhead of hg_poll_wait() in HG/NA perf benchmarks
=> HG/NA Perf: add spin_flag to prevent from excessively sleeping

src/util/mercury_log.c
=> HG log: fix buf overflow in `hg_log_get_subsys(void)`
