src/mercury.c
src/mercury.h
src/mercury_core.c
src/mercury_core.h

add HG_Context_get_class

---

src/mercury.c
src/mercury.h
src/mercury_core.c
src/mercury_core.h
src/na/na.c
src/na/na.h

This simply provides an HG API for the user to easily get at the class (not previously possible) and protocol (would have to parse HG_Addr_get_string) strings.

getters for HG class/protocol

---

src/util/mercury_poll.c

Reported by Chuck:
```
chuck@h0:/proj/TableFS/testU16/scripts/batch % fgrep 'Could not find fd in poll_set' /tmp/nex.log
```

Fix mercury poll to prevent concurrent accesses to poll set

---

Testing/mercury_rpc_cb.c
Testing/mercury_test.c
Testing/script/travis_build.sh
Testing/util/test_thread.c
Testing/util/test_time.c
src/CMakeLists.txt
src/mercury.c
src/mercury.h
src/mercury_bulk.c
src/mercury_bulk.h
src/mercury_core.c
src/mercury_core.h
src/mercury_core_header.c
src/mercury_core_header.h
src/mercury_core_types.h
src/mercury_header.c
src/mercury_header.h
src/mercury_hl.c
src/mercury_macros.h
src/mercury_private.h
src/mercury_proc.h
src/mercury_proc_buf.h
src/mercury_proc_bulk.h
src/mercury_types.h
src/na/na.c
src/util/CMakeLists.txt
src/util/mercury_thread_condition.h
src/util/mercury_time.h
src/util/mercury_util_config.h.in

Separate HG class from HG core class
Separate HG context from HG core context
Separate HG handle from HG core handle
Separate proc_bulk from mercury_proc.h

Rework mercury core layer to better separate HG layer from HG core layer

---

src/na/na_ofi.c

- add FI_COMPLETION flag
- fix pointer error in msg_rma.desc (necessary for providers using MR_BASIC)
Fixes #233

bug fixes to fi_writemsg() usage with verbs

---

src/na/na_ofi.c

fixes #240 
All optional parameters that vary by OFI provider are listed in a single macro at the top of na_ofi.c with this PR.  The code path keys off of these by indexing parameter arrays based on the provider enum.
The only remaining provider-specific conditionals in the communications path are there to deal with addressing differences.
The purpose of this PR is to make it less fragile to modify parameters for specific providers.

unify OFI provider-specific options in one macro

---

src/na/na_bmi.c

- differentiate tags used for different RMA control steps by reserving 8
bits of tag space
- this prevents (for example) the payload msg of one RMA operation from
colliding with a control msg of a different RMA, when the tags are
chosen by two different hosts independently

bug fix to bmi tags for internal RMA emulation

---

Testing/CMakeLists.txt
Testing/mercury_test.c
Testing/test_overflow.c
Testing/test_server.c
src/mercury.c
src/mercury_core.c
src/mercury_core.h
src/mercury_core_types.h
src/mercury_header.h
src/na/na_mpi.c

- HG Core: send ack once more data has been processed to release handle
- Testing: add overflow test back and clean up test server return codes

HG: add support for response overflow

---

Testing/test_cancel.c
src/mercury.h
src/mercury_core.c
src/mercury_core_types.h
src/na/na_ofi.c
src/na/na_types.h

NA OFI: return appropriate error code if operation cannot be canceled

---

Testing/mercury_test.c
Testing/mercury_test_drc.c
Testing/na/na_test.c
Testing/test_rpc.c
Testing/test_rpc_lat.c
Testing/test_write_bw.c
Testing/util/test_atomic.c
src/mercury_core.c
src/mercury_core_types.h
src/mercury_proc.c
src/na/na.c
src/na/na.h
src/na/na_cci.c
src/na/na_ofi.c
src/na/na_sm.c
src/na/na_types.h
src/util/mercury_atomic.h

Clean up tests and add rpc_lat, read_bw, write_bw to test suite
Fix shutdown of pool when using SEP
Clean up and fix init/finalize code
Add CMake option for max number of handles

NA OFI/SM: add support for retries

---

src/na/CMakeLists.txt
src/na/na_bmi.c
src/na/na_ip.c
src/na/na_ip.h
src/na/na_types.h

Also bring fixes from https://github.com/mercury-hpc/mercury/issues/342

NA BMI: bringing BMI fixes + ip addr fixes

---

src/mercury_core.c
src/na/na_ofi.c

HG: let NA callback propagate error to user

NA OFI: handle I/O errors that are returned from error CQ

---

src/na/na_ofi.c

When multiple client processes connect/send_msg to server, a race
condition possibly causes the same source to be inserted to AV multiple
times. The original code removes the fi_addr from AV, but if OFI AV
uses one slot for the multiple AV insert of same source, that will cause
some problems.
This patch refines it by checking the fi_addr and only removes it from AV
when the fi_addrs are different.

NA OFI: fix a potential bug in na_ofi_addr_ht_lookup

---

src/util/mercury_mem.c

Avoid querying pagesize every time
Signed-off-by: Johann Lombardi <johann.lombardi@intel.com>

util: refine hg_mem_get_page_size

---

src/util/mercury_atomic_queue.h

Fix build error in the "no atomics" case

---

src/na/na_ofi.c

If initial `fi_getinfo()` fails, then query libfabric to determine if the desired provider is available.  If not, then display a more helpful error message.
I'm marking this PR as a draft, because the resulting error message is somewhat cluttered by the additional context (function, line number, etc.) prepended by the logging functions:
```
"verbs" Mercury protocol) is not available.
"verbs;ofi_rxm" or use one of the following available providers:
tcp;ofi_rxm,tcp,sockets
...
```
Is there a logging variant that doesn't do that, or should we make one?  Or just leave it as is?

print verbose error if ofi provider not available

---

src/na/na_bmi.c

NA BMI: prevent progress_unexpected from racing with main progress function

---

src/mercury_core.c
src/na/na_sm.c
src/util/mercury_poll.c
src/util/mercury_poll.h

HG Util: Improve handling on EINTR errors in hg_poll_wait() (fix #392)

---

src/mercury_core.c

Skip processing input if NA recv error occurred

HG core: make sure handle is not released until cancelation is processed

---

src/na/na.c
src/na/na_bmi.c
src/na/na_cci.c
src/na/na_mpi.c
src/na/na_ofi.c
src/na/na_plugin.h
src/na/na_sm.c

NA OFI: remove now unused refcount

NA: make sure completion callback is called after OP ID is released

---

Testing/driver/mercury_test_driver.cxx
Testing/na/na_test.h
src/na/na_ofi.c
src/na/na_plugin.h

A batch of minor changes to the main Hg sources that I have made during the UCX plugin development.

Minor fixes

---

src/mercury_bulk.c
src/mercury_core_types.h
src/na/na_ofi.c
src/na/na_types.h

NA OFI: return and convert OFI error codes back to upper layers (fix #437)
HG bulk: return specific error code from NA back to user (fix #312)

HG/NA: add HG_HOSTUNREACH / NA_HOSTUNREACH error codes

---

Testing/na/na_test.c
Testing/na/na_test.h
Testing/na/na_test_getopt.c
Testing/script/gh_script.cmake
src/na/na_bmi.c
src/na/na_mpi.c
src/na/na_ofi.c
src/na/na_types.h

NA OFI: add support for msg size hints and refactor domain open code
Add -Z na test option to control max msg size

NA: add max_unexpected_size and max_expected_size hints (fix #263)

---

src/na/na_bmi.c
src/na/na_ofi.c
src/na/na_sm.c
src/util/mercury_log.c

- NA SM addr fixes
- NA OFI cleanups and fixes

Support NA sends to self and misc NA fixes

---

src/na/na_ofi.c

NA OFI: add addr pool to prevent addr allocation on unexpected recv

---

Testing/mercury_test.c
Testing/na/na_test.c
src/mercury.c
src/na/na.c
src/na/na_error.h
src/util/mercury_log.c
src/util/mercury_log.h
src/util/mercury_util.c

Add get stream routines
Add option to execute routine within debug macro
Update testing to set default log levels
HG/NA: fix generation of subsys name string

HG util: fix log subsys to prevent setting duplicates

---

src/util/mercury_time.h

ppc/32 and ppc/64 do not support CLOCK_MONOTONIC_COARSE in vdso

On PPC systems default to gettimeofday() on ms resolution (fix #464)

---

src/util/mercury_time.h

Fixes for not using CLOCK_MONOTONIC_COARSE on PPC

---

Testing/mercury_test.c
Testing/na/na_test.c
Testing/na/na_test.h
Testing/na/test_lat_client.c
Testing/na/test_lat_server.c
src/na/na_ip.c
src/na/na_ip.h
src/na/na_types.h
src/util/mercury_mem.c
src/util/mercury_mem.h

NA: add thread modes
NA test: add support for polling in latency tests
NA IP: add na_ip_check_interface() that can be used by plugins to select IP interface to use
HG util: add hg_mem_header_alloc/free calls to allocate buffers with a preceding header

Expand support features for NA plugins

---

src/mercury_core.c

Let canceled operations return errors
Clean up hg_core_complete() to return void

HG core: fix handle cleanup when forward fails (fix #519)

---

src/mercury_bulk.c
src/mercury_core.c
src/mercury_core_header.c
src/mercury_private.h

HG Core: correctly forward NA error return code back to HG user callback

---

src/mercury_core.c

Clean up context unpost and only wait on created list

HG Core: fix potential issue on context destroy where handles could have been reposted

---

src/na/na_ofi.c

Abort retried ops after default 90s timeout
Abort ops to a target being retried after first NA_HOSTUNREACH error in CQ

NA OFI: improve handling of retries after FI_EAGAIN return code

---

src/na/na_ofi.c

Reinstate NA_OFI_VERIFY_PROV_DOM flag to NA_OFI_DOM_IFACE

NA OFI: ensure interface name is not used as domain name for verbs etc

---

Testing/script/gh_install_deps.sh
src/na/na_ucx.c

Switch unexpected recvs to use OP ID queue
Remove addr resolution and retry / connection ID exchange
Use double index map for looking up addresses
Clean up op reset

NA UCX: use UCP_FEATURE_AM for unexpected messages (only)

---

src/na/na_ofi.c

init info format is: NIC:PID (both or only one may be passed)
NIC is cxi[0-9], PID is [0-510]

NA OFI: add init info parsing for CXI provider

---

src/na/na_ucx.c

Co-authored-by: Joseph Moore <joseph.moore@intel.com>

NA UCX: fix potential double free of worker_addr

---

src/na/na_ofi.c

NA OFI: fix FI_XXX_CXI enum values if libfabric version < 1.15

---

src/mercury_bulk.c
src/mercury_core.c
src/na/na_ofi.c

NA OFI: tweak warning/debug log output

HG/HG Bulk: remove some NA_CANCELED event warnings

---

src/na/na_ofi.c

When NA_THREAD_MODE_SINGLE is passed, FI_THREAD_DOMAIN can be used
to relax default's FI_THREAD_SAFE thread mode.

NA OFI: add support for FI_THREAD_DOMAIN

---

src/mercury_bulk.c
src/mercury_core.c

Additional refactoring to resolve NA components
HG Bulk: add extra error checking to prevent class mismatch

HG Core: add extra error checking to prevent class mismatch

---

src/na/na_ofi.c

(opx tmp fix) Pass FI_COMPLETION to RMA ops as flag is currently not ignored

NA OFI: fix handling of extra caps to not always follow advertised caps

---

src/na/na_ucx.c

This fixes a port conflict between listener and connection ports

NA UCX: enforce src_addr port used for connections to 0

---

src/na/na_ofi.c

NA OFI: fix prov/opx which does not support FI_SOURCE_ERR

---

src/na/na_ofi.c

Separate code paths for providers that do not support FI_SOURCE

NA OFI: prevent use of FI_SOURCE with prov/cxi (performance)

---

Testing/common/mercury_test.c
Testing/common/na_test.c
Testing/common/na_test.h
Testing/unit/na/test_lookup.c

Number of targets was limited to UINT8_MAX

HG test: fix overflow of number of target / classes

---

src/na/na_ofi.c

Set domain ops to prevent memory corruptions

NA OFI: set CXI domain ops w/ slingshot 2.2

---

Testing/perf/na/na_bw_get.c
Testing/perf/na/na_bw_put.c
Testing/perf/na/na_lat.c
Testing/perf/na/na_perf.c
Testing/perf/na/na_perf.h

NA Perf: ensure perf tests wait on send completion

---

.github/workflows/ci.yml
src/na/na_ucx.c

allow na_ucx_get_protocol_info() to resolve ucx tl name aliases

NA UCX: fix hg_info not filtering protocol

---

src/na/na.c
src/util/mercury_log.c
src/util/mercury_log.h

NA: fix missing free of dynamic plugin entries

HG util: use destructor to free log outlets (fix #729)

---

src/mercury_core.c
src/mercury_core.h

Remove HG_Core_event_ready_loopback() from public API

HG Core: make HG_Core_event_ready() non-inline to fix NA dependency

---

src/mercury_core.c
src/na/na.c
src/na/na_ofi.c

HG: fix NA init info not correctly set from HG core

---

src/mercury.c
src/mercury.h
src/mercury_core.c
src/mercury_core.h
src/mercury_core_types.h
src/util/mercury_dlog.c
src/util/mercury_log.c
src/util/mercury_log.h

Add rpc_req_recv_active_count and rpc_multi_recv_copy_count counters

HG: add HG_Diag_dump_counters() to dump diagnostic counters

---

Testing/perf/hg/hg_bw_read.c
Testing/perf/hg/hg_bw_write.c
Testing/perf/hg/mercury_perf.c
Testing/perf/hg/mercury_perf.h
Testing/perf/na/na_bw_get.c
Testing/perf/na/na_bw_put.c
Testing/perf/na/na_perf.c
Testing/perf/na/na_perf.h

Reduce column size
Fix bulk permission flag in hg_bw_read

HG perf: print reg and dereg times when -R option is used

---

src/mercury.c
src/mercury_core_types.h
src/na/na_ofi.c
src/na/na_types.h
src/na/na_ucx.c

HG: add HG_IO return code and reserve space for additional NA codes
Update OFI and UCX plugins to use new code

NA: add NA_IO return code for generic I/O errors

---

src/na/CMakeLists.txt
src/na/na.c
src/na/na_config.h.in
src/util/mercury_dl.h

Calculate relative path at build time and use it at runtime to find the plugin directory

NA: Use relative path for NA plugin search

---

CMakeLists.txt
src/na/CMakeLists.txt
src/na/na.c
src/na/na_config.h.in
src/util/CMakeLists.txt
src/util/mercury_dl.c
src/util/mercury_dl.h

Clean up previous commit and use cmake_path()
Fix plugin scan to continue if one plugin cannot load

NA: remove NA_DEFAULT_PLUGIN_PATH and use NA_PLUGIN_RELATIVE_PATH

---

src/util/mercury_mem_pool.c

HG util: fix error return of hg_mem_pool_extend()

---

src/mercury_core.c
src/na/na_ofi.c

In rare cases, it is possible that the multi-recv buffer gets released by the provider without any actual buffer returned.
Fix HG core to handle this case.

NA OFI: fix case of FI_MULTI_RECV event returned without buffer

---

src/util/mercury_log.c

fix global buffer overflow in hg_log_outlet_active

---

src/na/na.c
src/na/na.h
src/na/na_bmi.c
src/na/na_ofi.c
src/na/na_sm.c

NA OFI: refactor msg_send/msg_recv calls and add debug info

NA: add na_context parameter to context_create plugin cb

---

src/na/na_ucx.c

Reject connection after timeout if no progress is made
This allows an existing connection to close properly before a new entry gets created.

NA UCX: queue up pending connection if addr exists

---

src/util/mercury_log.c

Order of constructor calls could have lead to parent registered last

HG util: ensure parent log is registered first

---

src/na/na.c

Clean up properly when plugin cannot be loaded

NA: fix plugin load when failure occurs

---

src/na/na_ofi.c

Disable until issues related to RNR are fixed

NA OFI: disable RNR protocol by default
